; This file was auto-generated by drush make
core = 7.x

api = 2

; Modules
projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.3"

projects[addressfield][subdir] = "contrib"
projects[addressfield][version] = "1.2"

projects[addressfield_cl][subdir] = "contrib"
projects[addressfield_cl][version] = "1.0-beta1"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc5"

projects[adminimal_admin_menu][subdir] = "contrib"
projects[adminimal_admin_menu][version] = "1.7"

projects[advanced_help][subdir] = "contrib"
projects[advanced_help][version] = "1.3"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.9"

projects[commerce][subdir] = "contrib"
projects[commerce][version] = "1.13"

projects[commerce_add_to_cart_confirmation][subdir] = "contrib"
projects[commerce_add_to_cart_confirmation][version] = "1.0-rc2"

projects[commerce_addressbook][subdir] = "contrib"
projects[commerce_addressbook][version] = "2.0-rc9"

projects[commerce_backoffice][subdir] = "contrib"
projects[commerce_backoffice][version] = "1.5"

projects[commerce_checkout_progress][subdir] = "contrib"
projects[commerce_checkout_progress][version] = "1.4"

projects[commerce_features][subdir] = "contrib"
projects[commerce_features][version] = "1.1"

projects[commerce_khipu][subdir] = "contrib"
projects[commerce_khipu][version] = "1.0-beta2"

projects[commerce_migrate][subdir] = "contrib"
projects[commerce_migrate][version] = "1.2"

projects[commerce_search_api][subdir] = "contrib"
projects[commerce_search_api][version] = "1.4"

projects[commerce_shipping][subdir] = "contrib"
projects[commerce_shipping][version] = "2.2"

projects[commerce_webpay][subdir] = "contrib"
projects[commerce_webpay][version] = "1.0-rc2"

projects[date][subdir] = "contrib"
projects[date][version] = "2.9"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.7"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"

projects[eva][subdir] = "contrib"
projects[eva][version] = "1.2"

projects[facetapi][subdir] = "contrib"
projects[facetapi][version] = "1.5"

projects[features][subdir] = "contrib"
projects[features][version] = "2.10"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.5"

projects[inline_entity_form][subdir] = "contrib"
projects[inline_entity_form][version] = "1.8"

projects[khipu][subdir] = "contrib"
projects[khipu][version] = "1.0"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[migrate][subdir] = "contrib"
projects[migrate][version] = "2.8"

projects[migrate_extras][subdir] = "contrib"
projects[migrate_extras][version] = "2.5"


projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.3"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.9"

projects[search_api][subdir] = "contrib"
projects[search_api][version] = "1.18"

projects[search_api_db][subdir] = "contrib"
projects[search_api_db][version] = "1.5"

projects[search_api_ranges][subdir] = "contrib"
projects[search_api_ranges][version] = "1.5"

projects[title][subdir] = "contrib"
projects[title][version] = "1.0-alpha8"

projects[transliteration][subdir] = "contrib"
projects[transliteration][version] = "3.2"

projects[token][subdir] = "contrib"
projects[token][version] = "1.6"

projects[views][subdir] = "contrib"
projects[views][version] = "3.13"

projects[views_megarow][subdir] = "contrib"
projects[views_megarow][version] = "1.5"

projects[webpay][subdir] = "contrib"
projects[webpay][version] = "1.2"

; Themes
projects[omega][version] = "4.4"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[Khipu][download][type] = "file"
libraries[Khipu][download][url] = "https://github.com/Tifon-/Khipu/archive/v1.2.zip"
libraries[Khipu][directory_name] = "Khipu"
libraries[Khipu][type] = "library"

